
export type TransactionType = 'income' | 'expense' | 'investment';
export type TransactionStatus = 'paid' | 'pending' | 'in' | 'out';

export interface Category {
  id: string;
  name: string;
  type: 'income' | 'expense' | 'both' | 'investment';
  budget?: number; // Orçamento padrão ou atual
  budgetHistory?: {
    month: number;
    year: number;
    amount: number;
  }[];
  isActive?: boolean; // Se a categoria está ativa ou não
  inactivationMonth?: number;
  inactivationYear?: number;
}

export interface Despesa {
  id: string;
  title: string;
  amount: number;
  type: TransactionType;
  category: string;
  date: string;
  status: TransactionStatus;
  paymentDate?: string; // Data real do pagamento (para despesas pagas)
  createdAt?: string; // Data de criação do registro
  updatedAt?: string; // Data da última edição
  observation?: string; // Observações adicionais ou extraídas do recibo
  isFixed?: boolean; // Indica se é uma despesa fixa (recorrente)
  isAutoGenerated?: boolean; // Indica se foi gerado automaticamente pelo sistema
  isAdvancePayment?: boolean; // Indica se a parcela foi paga antecipadamente ("Pago Antecipado")
  installments?: {
    current: number;
    total: number;
    isAdvancePayment?: boolean;
  };
}

export type Transaction = Despesa;

export interface SummaryData {
  income: number;
  expense: number;
  total: number;
  pending: number;
}

export interface AIAnalysisResult {
  summary: string;
  tips: string[];
  anomalies: string[];
}

export interface AIAnalysis extends AIAnalysisResult {
  id: string;
  dataContextId: string;
  userId: string; // ID do usuário que gerou a análise
  createdAt: string;
  totalExpenses: number;
  totalIncome: number;
  totalInvestments: number;
  transactionCount: number;
}

export interface ReceiptData {
  title: string;
  amount: number;
  date: string;
  observation: string;
}

// Auth Types
export interface User {
  id: string;
  name: string;
  email: string;
  password?: string; // Em um app real, nunca armazene senhas em texto puro!
  parentId?: string; // Se pertencer a uma conta principal
  dataContextId: string; // ID usado para buscar os dados (pode ser o próprio ID ou do pai)
  members?: User[]; // Membros adicionados por este usuário
  role?: 'admin' | 'user'; // Nível de acesso
  themeColor?: 'orange' | 'blue' | 'pink' | 'green';
  financialMonthStartDay?: number; // Dia de início do mês financeiro (1-31)
  plan?: 'free' | 'premium'; // Plano de assinatura
  subscriptionEndDate?: string; // Data de término da assinatura
}
