
import { v4 as uuidv4 } from 'uuid';
import { supabase } from './supabaseClient';
import { Despesa, Category } from '../types';
import { INITIAL_CATEGORIES } from '../constants';

// Helper para limpar o payload antes de enviar ao Supabase
const sanitizeTransactionPayload = (despesa: Despesa, dataContextId?: string) => {
    return {
        ...(dataContextId ? { data_context_id: dataContextId } : {}),
        title: despesa.title,
        amount: despesa.amount,
        type: despesa.type,
        category: despesa.category,
        status: despesa.status,
        date: despesa.date,
        payment_date: despesa.paymentDate || null, // Garante NULL se vazio
        observation: despesa.observation || null,
        installments: despesa.installments || null, // Garante NULL se vazio (importante para fixas)
        is_fixed: despesa.isFixed === true, // Garante booleano
        is_auto_generated: despesa.isAutoGenerated === true
    };
};

export const dataService = {
  // --- CATEGORIAS ---
  fetchCategories: async (dataContextId: string, retries = 3): Promise<Category[]> => {
    if (!dataContextId) {
        console.warn("fetchCategories chamado sem dataContextId");
        return [];
    }

    for (let i = 0; i < retries; i++) {
        try {
            const timeoutPromise = new Promise<Category[]>((_, reject) => 
                setTimeout(() => reject(new Error('Tempo limite excedido ao buscar categorias.')), 15000)
            );

            const fetchPromise = (async () => {
                const { data, error } = await supabase
                  .from('categories')
                  .select('*')
                  .eq('data_context_id', dataContextId);
                
                if (error) {
                  console.error('Erro ao buscar categorias:', error);
                  throw error;
                }
                return data || [];
            })();

            return await Promise.race([fetchPromise, timeoutPromise]);
        } catch (error) {
            console.warn(`Tentativa ${i + 1} de buscar categorias falhou:`, error);
            if (i === retries - 1) throw error; // Se foi a última tentativa, lança o erro
            // Espera um pouco antes de tentar novamente (backoff)
            await new Promise(resolve => setTimeout(resolve, 1000 * (i + 1)));
        }
    }
    return [];
  },

  // Função para popular categorias iniciais se a conta for nova
  seedCategories: async (dataContextId: string): Promise<Category[]> => {
    if (!dataContextId) return [];

    const categoriesToInsert = INITIAL_CATEGORIES.map(cat => ({
        name: cat.name,
        type: cat.type,
        budget: 0,
        data_context_id: dataContextId
    }));

    const { data, error } = await supabase
        .from('categories')
        .insert(categoriesToInsert)
        .select();

    if (error) {
        console.error('Erro ao criar categorias iniciais:', error);
        throw error;
    }
    return data || [];
  },

  addCategory: async (category: Category, dataContextId: string): Promise<Category | null> => {
    const { data, error } = await supabase
      .from('categories')
      .insert({ ...category, data_context_id: dataContextId })
      .select()
      .single();
    
    if (error) {
      console.error(error);
      throw new Error('Erro ao salvar categoria');
    }
    return data;
  },

  updateCategory: async (category: Category): Promise<void> => {
    const { error } = await supabase
      .from('categories')
      .update({ name: category.name, type: category.type, budget: category.budget })
      .eq('id', category.id);
      
    if (error) throw error;
  },

  deleteCategory: async (id: string): Promise<void> => {
    const { error } = await supabase.from('categories').delete().eq('id', id);
    if (error) throw error;
  },

  // --- RESTAURAÇÃO DE BACKUP ---
  restoreBackup: async (user: any, backupData: any): Promise<void> => {
    if (!user || !user.dataContextId || !backupData) throw new Error("Dados inválidos para restauração");

    const categories = backupData.categories || [];
    const transactions = backupData.transactions || [];
    const members = backupData.members || [];

    // 0. Restaurar Membros
    if (members.length > 0) {
      const membersPayload = members.map((m: any) => ({
        id: m.id,
        name: m.name,
        email: m.email,
        parent_id: user.id, // Garante que fiquem vinculados ao usuário atual
        data_context_id: m.dataContextId || m.data_context_id || user.dataContextId,
        role: m.role || 'user',
        password: 'managed_profile' // Placeholder para manter o padrão
      }));

      // Usamos upsert para atualizar se já existir ou inserir se for novo
      const { error: memberError } = await supabase
        .from('app_users')
        .upsert(membersPayload, { onConflict: 'id' });
      
      if (memberError) {
        console.warn(`Aviso ao restaurar membros: ${memberError.message}`);
        // Não lançamos erro aqui para não travar a restauração dos dados principais
      }
    }

    // 1. Restaurar Categorias
    if (categories.length > 0) {
      const categoriesPayload = categories.map((cat: any) => ({
        id: cat.id,
        name: cat.name,
        type: cat.type,
        budget: cat.budget || 0,
        data_context_id: cat.data_context_id || cat.dataContextId || user.dataContextId
      }));

      const { error: catError } = await supabase
        .from('categories')
        .upsert(categoriesPayload);
      
      if (catError) throw new Error(`Erro ao restaurar categorias: ${catError.message}`);
    }

    // 2. Restaurar Transações
    if (transactions.length > 0) {
      const transactionsPayload = transactions.map((t: any) => ({
        id: t.id,
        data_context_id: t.data_context_id || t.dataContextId || user.dataContextId,
        title: t.title,
        amount: t.amount,
        type: t.type,
        category: t.category,
        status: t.status,
        date: t.date,
        payment_date: t.paymentDate || t.payment_date || null,
        observation: t.observation || null,
        installments: t.installments || null,
        is_fixed: t.isFixed === true || t.is_fixed === true,
        is_auto_generated: t.isAutoGenerated === true || t.is_auto_generated === true
      }));

      const { error: transError } = await supabase
        .from('transactions')
        .upsert(transactionsPayload);

      if (transError) throw new Error(`Erro ao restaurar transações: ${transError.message}`);
    }
  },

  // --- TRANSAÇÕES ---
  fetchTransactions: async (dataContextId: string): Promise<Despesa[]> => {
    const timeoutPromise = new Promise<Despesa[]>((_, reject) => 
        setTimeout(() => reject(new Error('Tempo limite excedido ao buscar transações.')), 10000)
    );

    const fetchPromise = (async () => {
        const { data, error } = await supabase
          .from('transactions')
          .select('*')
          .eq('data_context_id', dataContextId)
          .order('date', { ascending: false });

        if (error) {
          console.error('Erro ao buscar transações:', error);
          throw error;
        }
        
        return (data || []).map((t: any) => ({
          ...t,
          amount: Number(t.amount),
          paymentDate: t.payment_date,
          isFixed: t.is_fixed,
          isAutoGenerated: t.is_auto_generated
        }));
    })();

    return Promise.race([fetchPromise, timeoutPromise]);
  },

  addTransaction: async (despesa: Despesa, dataContextId: string): Promise<Despesa | null> => {
    const payload = {
        ...sanitizeTransactionPayload(despesa, dataContextId),
        id: despesa.id // ID é opcional no insert se for gerado pelo banco, mas mantemos se vier do front
    };

    const { data, error } = await supabase
      .from('transactions')
      .insert(payload)
      .select()
      .single();

    if (error) {
        console.error('Erro ao adicionar transação:', error);
        throw new Error('Erro ao salvar transação');
    }
    
    return { 
        ...data, 
        amount: Number(data.amount),
        paymentDate: data.payment_date,
        isFixed: data.is_fixed,
        isAutoGenerated: data.is_auto_generated
    };
  },

  updateTransaction: async (despesa: Despesa): Promise<void> => {
     const payload = sanitizeTransactionPayload(despesa);
     console.log('dataService.updateTransaction payload:', payload);

    const { error } = await supabase
      .from('transactions')
      .update(payload)
      .eq('id', despesa.id);
      
    if (error) {
        console.error('Erro ao atualizar transação:', error);
        throw error;
    }
  },

  deleteTransaction: async (id: string): Promise<void> => {
    const { error } = await supabase.from('transactions').delete().eq('id', id);
    if (error) throw error;
  },

  stopRecurringAndDeleteTransaction: async (id: string, dataContextId: string, despesa?: Despesa): Promise<void> => {
    let title = despesa?.title;
    let amount = despesa?.amount;
    let category = despesa?.category;
    let date = despesa?.date;

    if (!title || amount === undefined || !category || !date) {
        // 1. Busca a transação a ser excluída para pegar os detalhes
        const { data: transaction, error: fetchError } = await supabase
            .from('transactions')
            .select('*')
            .eq('id', id)
            .single();

        if (fetchError || !transaction) {
             console.warn('Transação não encontrada para parar recorrência. Tentando excluir apenas pelo ID.');
             // Se não existe, tentamos o delete direto apenas para garantir
             const { error: deleteError } = await supabase.from('transactions').delete().eq('id', id);
             if (deleteError) throw deleteError;
             return;
        }

        title = transaction.title;
        amount = transaction.amount;
        category = transaction.category;
        date = transaction.date;
    }

    // 2. Encontra e atualiza transações anteriores (pais) para não serem mais fixas
    // Critério: Mesmo título, valor, categoria, is_fixed=true e data anterior
    const { error: updateError } = await supabase
        .from('transactions')
        .update({ is_fixed: false })
        .eq('data_context_id', dataContextId)
        .eq('title', title)
        .eq('amount', amount)
        .eq('category', category)
        .eq('is_fixed', true)
        .lt('date', date);

    if (updateError) console.error('Erro ao parar recorrência:', updateError);

    // 3. Exclui a transação atual
    const { error: deleteError } = await supabase
        .from('transactions')
        .delete()
        .eq('id', id);

    if (deleteError) throw deleteError;
  },
  
  markAsPaid: async (ids: string[], paymentDate: string): Promise<void> => {
    const { error } = await supabase
        .from('transactions')
        .update({ status: 'paid', payment_date: paymentDate })
        .in('id', ids);
    if (error) throw error;
  },

  // Variável de controle para evitar execução simultânea
  _isGeneratingRecurring: false,

  // Nova função para verificar e gerar despesas recorrentes
  checkAndGenerateRecurringExpenses: async (currentTransactions: Despesa[], dataContextId: string): Promise<Despesa[]> => {
    // Evita execução simultânea
    if ((dataService as any)._isGeneratingRecurring) {
        console.log('Geração de recorrentes já em andamento. Pulando...');
        return [];
    }

    (dataService as any)._isGeneratingRecurring = true;

    try {
        // Filtra transações fixas (despesas, receitas e investimentos)
        const fixedTransactions = currentTransactions.filter(t => t.isFixed && (t.type === 'expense' || t.type === 'income' || t.type === 'investment'));
        const newTransactions: Despesa[] = [];
        const today = new Date();
        today.setHours(0, 0, 0, 0);

        for (const trans of fixedTransactions) {
            const dueDate = new Date(trans.date + 'T12:00:00');
            const triggerDate = new Date(dueDate);
            triggerDate.setDate(dueDate.getDate() + 20);

            if (today >= triggerDate) {
                const nextMonthDate = new Date(dueDate);
                nextMonthDate.setMonth(nextMonthDate.getMonth() + 1);
                
                // Ajuste para fim de mês (ex: 31/01 -> 28/02)
                if (nextMonthDate.getDate() !== dueDate.getDate()) {
                    nextMonthDate.setDate(0);
                }

                const nextDateStr = nextMonthDate.toISOString().split('T')[0];
                const targetMonthStart = nextDateStr.substring(0, 7) + '-01'; // YYYY-MM-01
                const targetMonthEnd = new Date(nextMonthDate.getFullYear(), nextMonthDate.getMonth() + 1, 0).toISOString().split('T')[0]; // YYYY-MM-LastDay

                // Verificação ROBUSTA no banco de dados para evitar duplicidade
                // Verifica se existe QUALQUER transação com mesmo título e categoria neste mês
                // Ignora valor e dia exato, foca na competência (mês/ano)
                const { count, error } = await supabase
                    .from('transactions')
                    .select('*', { count: 'exact', head: true })
                    .eq('data_context_id', dataContextId)
                    .ilike('title', trans.title.trim()) // Case-insensitive
                    .eq('category', trans.category)
                    .gte('date', targetMonthStart)
                    .lte('date', targetMonthEnd);

                if (error) {
                    console.error('Erro ao verificar duplicidade no banco:', error);
                    continue; // Pula se der erro para não arriscar duplicar
                }

                // Se count for 0, significa que NÃO existe registro similar neste mês
                if (count === 0) {
                    const newTrans: Despesa = {
                        id: uuidv4(),
                        title: trans.title,
                        amount: trans.amount,
                        type: trans.type,
                        category: trans.category,
                        // Para investimentos, mantemos o status (in/out) pois ele define a direção
                        // Para despesas/receitas, definimos como 'pending'
                        status: trans.type === 'investment' ? trans.status : 'pending',
                        date: nextDateStr,
                        isFixed: true,
                        isAutoGenerated: true,
                        installments: { current: 1, total: 1 },
                        observation: trans.observation,
                        createdAt: new Date().toISOString()
                    };
                    newTransactions.push(newTrans);
                }
            }
        }

        if (newTransactions.length > 0) {
            console.log(`Gerando ${newTransactions.length} transações recorrentes automáticas...`);
            
            const payload = newTransactions.map(t => ({
                ...sanitizeTransactionPayload(t, dataContextId),
                id: t.id
            }));

            const { error } = await supabase
                .from('transactions')
                .insert(payload);

            if (error) {
                console.error('Erro ao gerar transações recorrentes:', error);
                return [];
            }

            return newTransactions;
        }

        return [];
    } finally {
        (dataService as any)._isGeneratingRecurring = false;
    }
  }
};
