name: Deploy
on:
  push:
    branches:
      - main # Ou master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Adicione passos de build e deploy aqui
